typography_spectrum: 0.27306673559360206
color:
  brandStrength: 0.34409194346517324
  lightness: 0.9401726454962045
  saturation: 0.3649561395868659
  rhythmicContrast: 0.20723299193196
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.522933735512197
author:
  name: hightime
  email: hightime.rebellion@gmail.com
  url: hightimerebellion.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9b4de39a-6386-401e-a743-15addac907be.jpg
name: hightime rebellion
navigation: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/147f008d-7b1a-43cf-9113-e510fb9253c8.jpg
title: Freq
description: official website coming soon
