title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: official website coming soon
color:
  saturation: 0.7688172
  brandStrength: 0.01075269
  lightness: 0.7903226
  brandColors:
    - '#FCD8D8'
    - '#C04500'
    - '#F57F76'
    - '#E8AB96'
    - '#D1771B'
  rhythmicContrast: 0.2939068
navigation:
  - name: Youtube channel
    url: 'https://www.youtube.com/user/HightimeRebellion'
    type: external
  - name: twitter
    url: 'https://twitter.com/Hightimeband'
    type: external
  - name: instagram
    url: 'https://www.instagram.com/hightimerebellion/'
    type: external
  - name: news
    id: f4c3f5c9-d897-486e-b98b-979ebfb77b65
    type: content
  - name: about the band
    id: b79d27d4-c6b3-4365-bb8e-9a19172349b7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/147f008d-7b1a-43cf-9113-e510fb9253c8.jpg
name: hightime rebellion
author:
  name: hightime rebellion
  email: hightime.rebellion@gmail.com
  url: hightimerebellion
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9b4de39a-6386-401e-a743-15addac907be.jpg
typography_spectrum: 0.6738351
layout_spectrum: 0.03544006496667862
