typography_spectrum: 0.874241043580696
color:
  brandStrength: 0.9083972100634128
  lightness: 0.41644865507259965
  saturation: 0.7148869640659541
  rhythmicContrast: 0.29761153273284435
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
layout_spectrum: 0.03544006496667862
author:
  name: hightime
  email: hightime.rebellion@gmail.com
  url: thegrid.ai/hightimerebellion
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9b4de39a-6386-401e-a743-15addac907be.jpg
name: hightime rebellion
navigation:
  - name: Youtube channel
    url: 'https://www.youtube.com/user/HightimeRebellion'
    type: external
  - name: twitter
    url: 'https://twitter.com/Hightimeband'
    type: external
  - name: instagram
    url: 'https://www.instagram.com/hightimerebellion/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/147f008d-7b1a-43cf-9113-e510fb9253c8.jpg
title: HIGHTIME REBELLION
description: official website coming soon
